# Numpy

NumPy is a Python package providing fast, flexible, and expressive data structures designed to make working with 'relationa' or 'labeled' data both easy and intuitive

In [2]:
import numpy as np
print(np.__version__)
print(np.show_config)

1.14.3
<function show at 0x00000199360A01E0>


In [3]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [4]:
x= np.array([1,2,3,4])
print(x)
print(np.all(x))

[1 2 3 4]
True


In [5]:
y= np.array([0,2,3,4])
print(y)
print(np.all(y))

[0 2 3 4]
False


In [6]:
print(x)
print(np.any(x))

[1 2 3 4]
True


In [7]:
print(y)
print(np.any(y))

[0 2 3 4]
True


In [8]:
print(x)
print(np.isfinite(x))

[1 2 3 4]
[ True  True  True  True]


In [9]:
z= np.array([2,4,np.nan,np.inf])
print(z)
print(np.isfinite(z))

[ 2.  4. nan inf]
[ True  True False False]


In [10]:
print(np.isinf(z))

[False False False  True]


In [11]:
print(np.isnan(z))

[False False  True False]


In [12]:
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print(np.iscomplex(a))

[ True False False False False  True]


In [13]:
print(np.isreal(a))

[False  True  True  True  True False]


In [14]:
print(np.isscalar(3.1))

True


In [15]:
print(np.isscalar([3.1]))

False


In [16]:
print(np.greater(x,y))

[ True False False False]


In [17]:
print(np.greater_equal(y,x))

[False  True  True  True]


In [18]:
print(np.less(x,y))

[False False False False]


In [19]:
print(np.less_equal(x,y))

[False  True  True  True]


In [20]:
print(np.equal(x,y))

[False  True  True  True]


In [24]:
print("%d bytes" % (x.size * x.itemsize))

16 bytes


In [27]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [29]:
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [31]:
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [32]:
arr = np.arange(10,50,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [33]:
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
print(np.random.normal(0,1,1))

[-0.02319567]


In [36]:
print(np.random.normal(0,1,10))

[ 0.22909502 -0.94873021  0.65537393 -1.31639751 -0.82876404  2.22566344
 -1.22838204  0.65110562 -1.33519397  0.07189239]


In [41]:
ar = np.arange(2, 14).reshape((3,4))

print(ar)
for x in np.nditer(ar):
    print(x,end =" ")

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
2 3 4 5 6 7 8 9 10 11 12 13 

In [45]:
#change the sign of the numbers in the range from 9 to 15.
x = np.arange(20)
print(x)
x[(x >= 9) & (x <= 15)] *= -1
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19]


In [46]:
#vector of length 5 filled with arbitrary integers from 0 to 10.
x=np.random.randint(0,11,5)
print(x)

[9 4 0 4 2]


In [47]:
m= np.arange(10,22).reshape((3, 4))
print(m.shape)

(3, 4)


In [50]:
x=np.ones((10,10))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [51]:
x=np.diag([1,2,3,4,5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [53]:
x = np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [55]:
np.random.random((3,3,3))

array([[[0.58686076, 0.14852067, 0.66390202],
        [0.54837365, 0.59078562, 0.28563535],
        [0.24832997, 0.52599333, 0.40951697]],

       [[0.96526588, 0.99039431, 0.37236127],
        [0.48826102, 0.10077397, 0.15799268],
        [0.36850666, 0.56084188, 0.26327549]],

       [[0.47506916, 0.44703744, 0.84004634],
        [0.33384267, 0.3301674 , 0.60119791],
        [0.60137131, 0.08433145, 0.22372528]]])

In [56]:
print(np.sum(x))

8.0


In [57]:
print(np.sum(x, axis=0)) # column sum

[2. 2. 2. 2.]


In [58]:
print(np.sum(x, axis=1)) #row sum

[2. 2. 2. 2.]


In [59]:
x = np.array([4, 5])
y = np.array([7, 10])
print(np.dot(x, y))


78


In [62]:
x = np.arange(12).reshape((2, 6))
print(x)
r1=np.ptp(x,1)
r2=np.amax(x,1)-np.amin(x,1)

print(r1)
print(r2)
assert np.allclose(r1, r2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[5 5]
[5 5]


In [63]:
?np.ptp

In [65]:
x = np.arange(12).reshape((2, 6))

r1 = np.percentile(x, 80, 1)
print(x)
print(r1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 4. 10.]


In [67]:
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print(np.cov(x,y))

[[ 1. -1.]
 [-1.  1.]]


In [70]:
nums = np.array([70, 50, 20, 30, -11, 60, 50, 40])
print("Original array:")
print(nums)
print("\nAfter partitioning on 4 the position:")
print(np.partition(nums, 1))

Original array:
[ 70  50  20  30 -11  60  50  40]

After partitioning on 4 the position:
[-11  20  50  30  70  60  50  40]
